//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandlordV3_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationData()
        {
            this.TenantDatas = new HashSet<TenantData>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid PersonalID { get; set; }
        public string FileLoc { get; set; }
        public System.DateTime EntryTS { get; set; }
        public Nullable<bool> Approval { get; set; }
        public Nullable<System.DateTime> DecisionTS { get; set; }
        public Nullable<System.Guid> PropertyAddressID { get; set; }
        public string FirstBankStatementLoc { get; set; }
        public string SecondBankStatementLoc { get; set; }
        public string ThirdBankStatementLoc { get; set; }
        public string FirstCreditStatementLoc { get; set; }
        public string SecondCreditStatementLoc { get; set; }
        public string ThirdCreditStatementLoc { get; set; }
    
        public virtual PersonalData PersonalData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantData> TenantDatas { get; set; }
        public virtual Property_Address Property_Address { get; set; }
    }
}
