//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandlordV3_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplianceData
    {
        public System.Guid ID { get; set; }
        public System.Guid PropertyID { get; set; }
        public System.Guid TypeID { get; set; }
        public bool Electric { get; set; }
        public bool Gas { get; set; }
        public bool Fuel { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Serial { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Notes { get; set; }
        public string ModelLoc { get; set; }
        public Nullable<System.Guid> BusinessID { get; set; }
        public string RecieptLoc { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public string InstallationInvoiceLoc { get; set; }
        public Nullable<System.DateTime> WarrantyEndDate { get; set; }
        public string WarrantyLoc { get; set; }
        public System.DateTime EntryTS { get; set; }
    
        public virtual BusinessData BusinessData { get; set; }
        public virtual ApplianceType ApplianceType { get; set; }
        public virtual PropertyData PropertyData { get; set; }
    }
}
