//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandlordV3_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Address
    {
        public System.Guid ID { get; set; }
        public System.Guid AddressID { get; set; }
        public System.Guid BusinessID { get; set; }
    
        public virtual AddressData AddressData { get; set; }
        public virtual BusinessData BusinessData { get; set; }
    }
}
