//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandlordV3_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncludedData
    {
        public System.Guid ID { get; set; }
        public System.Guid PropertyID { get; set; }
        public bool Electricity { get; set; }
        public bool Gas { get; set; }
        public bool Water { get; set; }
        public bool Sewer { get; set; }
        public bool Waste { get; set; }
        public System.DateTime EntryTS { get; set; }
    
        public virtual PropertyData PropertyData { get; set; }
    }
}
