//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandlordV3_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginData
    {
        public System.Guid ID { get; set; }
        public string Email { get; set; }
        public bool ValidEmail { get; set; }
        public string Password { get; set; }
        public System.Guid RoleID { get; set; }
        public System.DateTime EntryTS { get; set; }
        public System.DateTime LastLogin { get; set; }
    
        public virtual LoginRole LoginRole { get; set; }
    }
}
