//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandlordV3_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetData
    {
        public System.Guid ID { get; set; }
        public System.Guid ReferenceID { get; set; }
        public string Type { get; set; }
        public string Breed { get; set; }
        public string Weight { get; set; }
        public string Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string PhotoLoc { get; set; }
        public System.DateTime EntryTS { get; set; }
    
        public virtual PersonalData PersonalData { get; set; }
    }
}
