//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandlordV3_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property_Address()
        {
            this.Tenant_Address = new HashSet<Tenant_Address>();
            this.ApplicationDatas = new HashSet<ApplicationData>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid AddressID { get; set; }
        public System.Guid PropertyID { get; set; }
    
        public virtual AddressData AddressData { get; set; }
        public virtual PropertyData PropertyData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tenant_Address> Tenant_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationData> ApplicationDatas { get; set; }
    }
}
