//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandlordV3_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant_Address
    {
        public System.Guid ID { get; set; }
        public System.Guid Property_AddressID { get; set; }
        public System.Guid TenantID { get; set; }
    
        public virtual Property_Address Property_Address { get; set; }
        public virtual TenantData TenantData { get; set; }
    }
}
